// <auto-generated />
namespace KeelteKooli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixTeacherTraining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixTeacherTraining));
        
        string IMigrationMetadata.Id
        {
            get { return "202601220926517_FixTeacherTraining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
