// <auto-generated />
namespace KeelteKooli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class KrutoiOchen1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KrutoiOchen1));
        
        string IMigrationMetadata.Id
        {
            get { return "202603041321435_KrutoiOchen1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
