// <auto-generated />
namespace KeelteKooli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRegistrationsToTraining2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRegistrationsToTraining2));
        
        string IMigrationMetadata.Id
        {
            get { return "202601220901454_AddRegistrationsToTraining2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
